[package]
name = "retrieval-experiments"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
ahash = "0.8.12"
anyhow = "1.0.104"
clap = "4.6.5"
consensus-retrieval = { path = "../consensus-retrieval" }
csv = "1.4.0"
erased-serde = "0.4.10"
rand = "0.10.2"
rand_distr = "0.6.0"
serde = { version = "1.0.229", features = ["serde_derive"] }
serde_json = "1.0.151"

[build-dependencies]
cmake = "0.1"

[profile.release]
lto = true
# codegen-units = 1
